#!/data/data/com.termux/files/usr/bin/node

const options = {};

// Handle CLI Arguments

process.argv.forEach((val, index) => {
  if (index < 2) return;
  const option = val.split('=');
  options[option[0]] = option[1];
});

// Read JSON data

const fs = require('fs');
const terms = JSON.parse(
  fs.readFileSync(`./src/terms/${ options['--lang'] ?? 'jp' }.json`)
);
const printed = [];

while (printed.length != terms.length) {
  const i = Math.floor(Math.random() * terms.length);
  const term = terms[i];
  if (printed.indexOf(term) >= 0) continue;
  printed.push(term);
}

// Main loop

let index = 0;

function next() {
  console.log((index+1) + ". " + printed[index]);
  index++;
  if (index + 1 === printed.length) return;
  setTimeout(next, options['--interval'] ?? 1000);
}

next();
